//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gourou.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gourou.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRFt5UAgx6y7cdt1fRVTBcts8kQHzdHyDlWl9p0/HRlQBEw04CHko5VVHdobtBdY1JNXahkfs0Oa8R79zU7AsThghqjuCgiO2fmnztfLRIGlnK/Kgy3Q9aJJ+sp35fpRV7c0nOifXPWniqz8CBvqvWHJ5W3BsXXH+czxNRr/GHXCCvQUWSy0vLjYPhxLVexpIM6kNExdhohyRLg64l5DARBxXl+9DYxMyLlSi5Zpb37n9efqUsGC8p5BbR7ApAWRot45zr2YMpD8iKLKUxe2qgIYluVJIo7fpXOv6dd5oG18P6/pYNfDsVZdJSikVd9R3rePi1yhQCdKvp/oQ7gMsD4JY6ZJ8JDFHHwmdUBloKqZiTRwDcCPCJRabndGQIc1H0yFltw0FZM5onn5qDUvUi+666ne0pp2TF4z7i76gzfe3fK2ENHbYcLrQidwLwOLJqrPRCMYOapvymrUS6mDJhT5wXSNmHjIku65b/4/9Ft+4bw4F3MJE5Y1EojtPE6w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dellksqldksqlkdlsqkdqs {
            get {
                return ResourceManager.GetString("dellksqldksqlkdlsqkdqs", resourceCulture);
            }
        }
    }
}
